#!/usr/bin/env python3
import os
import datetime
import pandas as pd

pd.set_option('display.max_rows', None)
script_dir = os.path.dirname(os.path.realpath(__file__))


def main():
    data = load_data()
    dates = data['date']

    dates0 = dates[0:-1].reset_index(drop=True)
    dates1 = dates[1:].reset_index(drop=True)
    date_diff = dates1 - dates0
    date_diff = date_diff.apply(lambda x: abs(x.days))

    for i, diff in enumerate(date_diff):
        # date is same as date on previous index
        if diff == 0:
            print(f"Duplicate date: {dates0[i].strftime('%d-%m-%Y')}")

        # there is a hole of n > 1 days
        if diff > 1:
            for offset in range(1, diff):
                missing = dates0[i] + pd.Timedelta(days=offset)
                print(f"Missing date: {missing.strftime('%d-%m-%Y')}")


def load_data():
    data_path = os.path.join(script_dir, '..', 'covid.csv')
    data = pd.read_csv(data_path)

    data['date'] = data['date'].apply(parse_date)
    data = data.sort_values('date').reset_index(drop=True)
    return data


def parse_date(dateStr):
    return datetime.datetime.strptime(dateStr, '%d-%m-%Y')


main()
