name: Update data

on:
  schedule:
    # Runs at midnight daily
    - cron: '0 10 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  scrape:
    name: Run spider
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: pip install .
    - name: Run spider
      run: scrapy crawl covid
    - name: Commit report
      run: |
        git config --global user.name 'Georgi Sabev'
        git config --global user.email 'georgethebeatle@gmail.com'
        git add covid.csv lowerbound.txt
        git commit -m "Update data"
        git push
